BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Version" (
	"Id"	INTEGER NOT NULL,
	"VersionNr"	INTEGER NOT NULL,
	PRIMARY KEY("Id")
);

DELETE FROM "Version";
INSERT INTO "Version" ("Id","VersionNr") VALUES (1,1);
COMMIT;
