PRAGMA foreign_keys=ON;
PRAGMA recursive_triggers=ON;
CREATE TABLE IF NOT EXISTS [RouteAssets] (
    [Id] INTEGER  Primary Key NOT NULL
    , [RouteId]	INTEGER  REFERENCES Routes (Id) ON DELETE CASCADE ON UPDATE NO ACTION
    , [AssetId] INTEGER  REFERENCES Assets (Id) ON DELETE CASCADE ON UPDATE NO ACTION
, UNIQUE(RouteId,AssetId)
);