INSERT OR IGNORE INTO Countries (CountryName,CountryAbbrev, Favorite)
VALUES
('Unknown','--',1)
,('Other','--',1)
,('Albania','AL',0)
,('Algeria','DZ',0)
,('Argentina','AR',0)
,('Armenia','AM',0)
,('Australia','AU',0)
,('Austria','AT',0)
,('Belgium','BE',0)
,('Bolivia','BO',0)
,('Bosnia and Herzegovina','BA',0)
,('Botswana','BW',0)
,('Brazil','BR',0)
,('Bulgaria','BG',0)
,('Canada','CA',1)
,('China','CN',1)
,('Colombia','CO',0)
,('Congo','CG',0)
,('Croatia','HR',0)
,('Cuba','CU',0)
,('Czech Republic','CZ',0)
,('Denmark','DK',0)
,('Ecuador','EC',0)
,('Egypt','EG',0)
,('Estonia','EE',0)
,('Finland','FI',0)
,('France','FR',1)
,('Germany','DE',1)
,('Greece','GR',0)
,('Greenland','GL',0)
,('India','IN',0)
,('Indonesia','ID',0)
,('Iran','IR',0)
,('Iraq','IQ',0)
,('Ireland','IE',0)
,('Israel','IL',0)
,('Italy','IT',0)
,('Jamaica','JM',0)
,('Japan','JP',0)
,('Jordan','JO',0)
,('Kazakhstan','KZ',0)
,('Kenya','KE',0)
,('Korea','KR',0)
,('Latvia','LV',0)
,('Lithuania','LT',0)
,('Luxembourg','LU',0)
,('Macedonia','MK',0)
,('Malaysia','MY',0)
,('Mexico','MX',0)
,('Monaco','MC',0)
,('Montenegro','ME',0)
,('Morocco','MA',0)
,('Mozambique','MZ',0)
,('Namibia','NA',0)
,('Nepal','NP',0)
,('Netherlands','NL',1)
,('New Zealand','NZ',0)
,('Nigeria','NG',0)
,('Pakistan','PK',0)
,('Panama','PA',0)
,('Paraguay','PY',0)
,('Peru','PE',0)
,('Philippines','PH',0)
,('Poland','PL',0)
,('Portugal','PT',0)
,('Qatar','QA',0)
,('Romania','RO',0)
,('Russian Federation','RU',0)
,('Saudi Arabia','SA',0)
,('Senegal','SN',0)
,('Serbia','RS',0)
,('Slovakia','SK',0)
,('South Africa','ZA',0)
,('Spain','ES',0)
,('Suriname','SR',0)
,('Sweden','SE',0)
,('Switzerland','CH',1)
,('Tanzania','TZ',0)
,('Thailand','TH',0)
,('Tunisia','TN',0)
,('Turkey','TR',0)
,('Ukraine','UA',0)
,('United Kingdom','GB',1)
,('United States','US',1)
,('Uruguay','UY',0)
,('Venezuela','VE',0)
,('Viet Nam','VN',0)
,('Zambia','ZM',0)
,('Zimbabwe','ZW',0);